//
// This file was generated by the JPA Modeler
//
package org.byfc.wikibooks_jpa._06_entities.many_to_many_bidirectional;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

@Entity

public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String firstName;
    private String lastName;
    private Double salary;
    @ManyToMany
    @JoinTable(
            name = "EMP_PROJ",
            joinColumns = @JoinColumn(name = "EMP_ID", referencedColumnName = "ID"),
            inverseJoinColumns = @JoinColumn(name = "PROJ_ID", referencedColumnName = "ID"))
    private List<Project> projects;

    public void addProject(Project project) {
        if (projects == null) {
            projects = new ArrayList<>();
        }
        if(!projects.contains(project))
            this.projects.add(project);
        else
            System.out.println(getFirstName()+" is already in the project");
    }

    public Employee() {

    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * @return the projects
     */
    public List<Project> getProjects() {
        return projects;
    }

    /**
     * @param projects the projects to set
     */
    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

}
