//
// This file was generated by the JPA Modeler
//
package org.byfc.wikibooks_jpa._08_entities.embedded_shared;

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity

public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String firstName;
    private String lastName;
    private Double salary;
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "startDate", column = @Column(name = "START_DATE")),
        @AttributeOverride(name = "endDate", column = @Column(name = "END_DATE"))
    })
    private EmploymentPeriod employmentPeriod;

    public Employee() {
        employmentPeriod = new EmploymentPeriod();
        String sDateS = "2000-11-01";
        java.sql.Date sDate = java.sql.Date.valueOf(sDateS);
        employmentPeriod.setStartDate(sDate);

        String eDateS = "2016-03-08";
        java.sql.Date eDate = java.sql.Date.valueOf(eDateS);
        employmentPeriod.setEndDate(eDate);

    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * @return the employmentPeriod
     */
    public EmploymentPeriod getEmploymentPeriod() {
        return employmentPeriod;
    }

    /**
     * @param employmentPeriod the employmentPeriod to set
     */
    public void setEmploymentPeriod(EmploymentPeriod employmentPeriod) {
        this.employmentPeriod = employmentPeriod;
    }

    
}
