//
// This file was generated by the JPA Modeler
//
package org.byfc.wikibooks_jpa._02_entities.many_to_one;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity

public class Phone implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String area_code;
    private String phonenumber;
    private String type;

    @ManyToOne(targetEntity = Employee.class)
    @JoinColumn(name="OWNER_ID")
    private Employee owner;

    public Phone() {

    }

    public String getArea_code() {
        return this.area_code;
    }

    public void setArea_code(String area_code) {
        this.area_code = area_code;
    }

    public String getPhonenumber() {
        return this.phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /**
     * @return the owner
     */
    public Employee getOwner() {
        return owner;
    }

    /**
     * @param owner the owner to set
     */
    public void setOwner(Employee owner) {
        this.owner = owner;
    }

}
