//
// This file was generated by the JPA Modeler
//
package org.byfc.wikibooks_jpa._04_entities.one_to_many_with_join_table;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;

@Entity

public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String firstName;
    private String lastName;
    private Double salary;
    @OneToMany
    @JoinTable(
            name = "EMP_PHONE",
            joinColumns = {
                @JoinColumn(name = "EMP_ID", referencedColumnName = "ID")},
            inverseJoinColumns = {
                @JoinColumn(name = "PHONE_ID", referencedColumnName = "ID", unique = true)}
    )
    private List<Phone> phones;

    // maintain bi-directional relationship
    public void addPhone(Phone phone) {
        if (phones == null) {
            phones = new ArrayList<>();
        }
        this.phones.add(phone);
        if (phone.getOwner() != this) {
            phone.setOwner(this);
        }
    }

    public Employee() {

    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * @return the phones
     */
    public List<Phone> getPhones() {
        return phones;
    }

    /**
     * @param phones the phones to set
     */
    public void setPhones(List<Phone> phones) {
        this.phones = phones;
    }
}
