//
// This file was generated by the JPA Modeler
//
package org.byfc.wikibooks_jpa._07_entities.embedded;

import java.io.Serializable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity

public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String firstName;
    private String lastName;
    private Double salary;
    @Embedded
    private EmploymentPeriod period;

    public Employee() {
        period = new EmploymentPeriod();
        String sDateS = "2000-11-01";
        java.sql.Date sDate = java.sql.Date.valueOf(sDateS);
        period.setStartDate(sDate);
        
        String eDateS = "2016-03-08";
        java.sql.Date eDate = java.sql.Date.valueOf(eDateS);
        period.setEndDate(eDate);
        
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * @return the period
     */
    public EmploymentPeriod getPeriod() {
        return period;
    }

    /**
     * @param period the period to set
     */
    public void setPeriod(EmploymentPeriod period) {
        this.period = period;
    }

}
